### ISSUE TITLE
Servicing stacks applied in incorrect order

### ISSUE THREAD

**Issue by manuelphazelton** [OSDeploy/OSBuilder.Public#1]
After importing the the original Windows 10 Enterprise 1607 x64 source media (14393.0), ran the following,

`Get-OSBuilderUpdates -UpdateCatalogs`
`Get-OSBuilderUpdates -FilterOS 'Windows 10' -FilterOSBuild 1607 -Download -RemoveSuperseded`
`Update-OSMedia -ByName "Win10 Ent 2016 LTSB x64 1607 14393.0" -Execute`

When updating, OSBuilder starts with the WinPE updates and tries to apply the new 2018-11 Servicing Stack Update for Windows 10 1607 x64 (KB4465659)  before the 2018-05 Servicing Stack Update for Windows 10 1607 x64 (KB4132216).

This causes Update-OSMedia to fail when running Add-WindowsPackage for the 2018-11 Servicing Stack Update. DISM errors out with `0x800F081E - CBS_E_NOT_APPLICABLE`.
After manually applying the 2018-05 Servicing Stack Update first, OSBuilder is able to successfully install the 2018-11 update.

**Comment by OSDeploy** [comment]
This was resolved in 18.11.30+.  Can you validate?

**Comment by OSDeploy** [comment]
No reply, but this should be resolved.  Closing!
Thanks for letting me know!
